# Configuration of DoubleTickets bot
[bot]
# Enter bot token
bot-token = ""
# Enter DO_NOT_DISTURB, ONLINE, IDLE, INVISIBLE, OFFLINE
status = "ONLINE"
# Change activity every <number> in seconds
activity-change-every = 60
# Put all members in guilds in database?
put-all-members-to-database = true

# Multiples bots feature
# [bot.other]