# Configure your tickets here.
[[ticket]]
type = "BUTTON_INTERACTION"
id = "ticketspremium"
title = "Create ticket"
description = "Create ticket for get support"
embed-color = "#ed6f07"
button-ids = [
    "btn2",
    "btn1"
]