# Configure text for cmds
[[commands]]
    name = "ticketembed"
    description = "This command create embed for interact with ticket system"
    permissions = [ # Name of user or role
        "mani123#7703"
    ]
    action-ids = [
        "CREATE_TICKET_EMBED_BUTTON"
    ]