[commands]
ticketembed.name = "ticketembed"
ticketembed.description = "This command create embed for interact with ticket system"
ticketembed.permission = "perm1role " # Name or id of role or user
[embeds]
error.button.title = "🔴 Error"
error.button.description = "This button is wrong"