# Configuration of DoubleTickets bot
[bot-ticket]
# Enter DO_NOT_DISTURB, ONLINE, IDLE, INVISIBLE, OFFLINE
status = "ONLINE"
# change activity every <number> in seconds
activity-change-every = 10
# Soon
# [bot.other]