# Enter type.<PLAYING, STREAMING, LISTENING, WATCHING, COMPETING>
# url - working only with STREAMING and stram sites, like YouTube and Twitch
[[activity]]
    activity-text = "Twitch stream"
    activity-type = "STREAMING"
    url = "https://www.google.com/"

[[activity]]
    activity-text = "YouTube stream"
    activity-type = "STREAMING"
    url = "https://www.google.com/"

[[activity]]
    activity-text = "GTA V"
    activity-type = "PLAYING"