[[commands]]
    name = "ticketembed"
    description = "This command create embed for interact with ticket system"
    permission = "mani123#7703 " # Name of user or role
    action = "CREATE_TICKET_EMBED"
[embeds]
    error.button.title = "🔴 Error"
    error.button.description = "This button is wrong"
    success.cmd.title = "🟢 Success"
    success.cmd.description = "This command was completed successfully"