# Configuration of DoubleTickets bot
[bot-custom]
activity = "PLAYING" # Enter PLAYING, STREAMING, LISTENING, WATCHING, COMPETING
activity-text = "tickets %tickets%" # Enter custom activity text, for get count of tickets use %tickets%
status = "ONLINE" # Enter DO_NOT_DISTURB, ONLINE, IDLE, INVISIBLE, OFFLINE

# Configure your tickets here.
[[ticket]]
type = "TICKET_BUTTON"
id = "tickets"
title = "Create ticket"
description = "Create ticket for get support"
embed-color = "#ed6f07"
category = "997558530037010593"
button-style = "SUCCESS"
button-id = "btn2"
button-text = "😋 Create Ticket"
[[ticket]]
type = "TICKET_BUTTON"
id = "ticketspremuim"
title = "Create premuim ticket"
description = "Create ticket for get premuim support"
embed-color = "#ed6f07"
category = "997558530037010593"
button-style = "SUCCESS"
button-id = "btn1"
button-text = "😋 Create a premuim Ticket"