# Configuration of DoubleTickets bot
[bot-ticket]
# Enter DO_NOT_DISTURB, ONLINE, IDLE, INVISIBLE, OFFLINE
status = "ONLINE"
# Change activity every <number> in seconds
activity-change-every = 60

# Multiples bots feature
# [bot.other]