# Configuration of DoubleTickets bot
[bot-ticket]
# Enter DO_NOT_DISTURB, ONLINE, IDLE, INVISIBLE, OFFLINE
status = "ONLINE"
# change activity every <number> in seconds
activity-change-every = 10

# Enter activity.<PLAYING, STREAMING, LISTENING, WATCHING, COMPETING>
[[activity]]
    activity-text = "Minecraft"
    type = "PLAYING"

[[activity]]
    activity-text = "Minecraft stream"
    type = "STREAMING"

[[activity]]
    activity-text = "GTA V stream"
    type = "STREAMING"
# Soon
# [bot.other]