# Configure interaction methods
[[interaction]]
    type = "BUTTON_INTERACTION"
    button-style = "SUCCESS"
    button-text = "😋 Create Ticket"
    id = "btn2"
    action-ids = [
        "MyAction1",
        "MyAction2"
    ]

[[interaction]]
    type = "BUTTON_INTERACTION"
    button-style = "SUCCESS"
    button-text = "Create Ticket"
    id = "btn1"
    action-ids = [
        "MyAction1",
        "MyAction2"
    ]