# Configure default text for embeds
[action-filed]
    reply-title = "🔴 Error"
    reply-description = "Dear %username-mentioned%, your action is filed"
    reply-isEphemeral = true
[action-success]
    reply-title = "🟢 Success"
    reply-description = "Dear %username-mentioned%, your action is success"
    reply-isEphemeral = true
[other]
    not-perms-title = "🟠 Hey"
    not-perms-description = "Dear %username-mentioned%, you don`t have perms"
