# Configure text for embeds
[embeds]
    error-title = "🔴 Error"
    error-description = "Dear %username-mentioned%, you has %action% error"
    success-title = "🟢 Success"
    success-description = "Dear %username-mentioned%, your %action% has completed"
    not-perms-title = "🟠 Hey"
    not-perms-description = "Dear %username-mentioned%, you don`t have %action%"
