# Configuration of DoubleTickets bot
[bot.ticket]
    activity = "PLAYING" # Enter PLAYING, STREAMING, LISTENING, WATCHING, COMPETING
    activity-text = "tickets %tickets%" # Enter custom activity text, for get count of tickets use %tickets%
    status = "ONLINE" # Enter DO_NOT_DISTURB, ONLINE, IDLE, INVISIBLE, OFFLINE
# Soon
# [bot.other]