[[action]]
    id = "MyAction1"
    type = "CREATE_VOICE_CHAT"
    action-name = "%username%-%counter%"
    counter = 1
    category-name = "test"
[[action]]
    id = "MyAction2"
    type = "CREATE_TEXT_CHAT"
    action-name = "%username%-%counter%"
    action-description = "Username: %username% Data: %data%"
    counter = 1
    category-name = "test"
[[action]]
    id = "MainAction"
    type = "CREATE_BUTTON_EMBED"
    embed-title = "%username% lol"
    embed-description = "Username: %username% Data: %data%"
    embed-color = "#ed6f07"
    button-ids = [
        "btn2",
        "btn1"
    ]