# Configure text for embeds
[command]
    success-title = "🟢 Success"
    success-description = "Dear %username-mentioned%, your command has completed"
    ephemeral = true
[button]
    success-title = "🟢 Success"
    success-description = "Dear %username-mentioned%, your interaction with button has completed"
    ephemeral = true
[other]
    error-title = "🔴 Error"
    error-description = "Dear %username-mentioned%, you has error"
    not-perms-title = "🟠 Hey"
    not-perms-description = "Dear %username-mentioned%, you don`t have perms"
