
[[interaction]]
    type = "Button"
    button-id = "btn2"
    button-style = "SUCCESS"
    button-text = "😋 Create Ticket"
    action = "CREATE_TEXT_CHAT"
    action-name = "%username%-%counter%"
    action-title = "Username: %username% Data: "
    counter = 0
    category = "997558530037010593"
[[interaction]]
    type = "Button"
    button-id = "btn1"
    button-style = "SUCCESS"
    button-text = "😋 Create a premuim Ticket"
    action = "CREATE_VOICE_CHAT"
    action-name = ""
    counter = 0
    category = "997558530037010593"

