# Configure text for cmds
[[commands]]
    name = "createEmbed"
    description = "This command create embed for interact with MainAction system"
    permissions = [ # Name of user or role
        "mani123#7703"
    ]
    action-ids = [
        "MainAction"
    ]