
# Configure command interactions
[[interaction]]
    actionsIds = ["mutecommand"]
    name = "mute"
    description = "mute selected user"
    optionIds = ["users"]
    botIds = ["792689746156978207"]
    allow-users = ["mani123#7703"]
    #allow-roles = []

# you can use only message and embed actions
[interaction.success]
    IsEphemeral = true
    actionId = "sendsuccessmessage"

# you can use only message and embed actions
[interaction.error]
    IsEphemeral = true
    actionId = "senderrormessage"

[interaction.option]

[interaction.option.users]
    name = "user"
    description = "List of users"
    type = "user"
    required = true

