
# Configure command interactions
[[interaction]]
	actionsIds = ["muteAction", "defaineAction", "sendSuccessMuteEmbed"]
	name = "mute"
	description = "mute selected user"
	optionIds = ["users"]
	filtersIds = ["myfilter"]

[[interaction]]
actionsIds = ["unmuteAction", "undefaineAction", "sendSuccessMuteEmbed"]
	name = "unmute"
	description = "unmute selected user"
	optionIds = ["users"]
	filtersIds = ["myfilter"]

[option.users]
	name = "listofusers"
	description = "List of users"
	type = "user"
	required = true

[filter.myfilter]
	type = "USER"
	list = ["mani123#7703"]
	filter-actions = ["sendErrorMuteEmbed"]

