
# Configure command interactions
[[interaction]]
	actionsIds = ["mutecommand", "DEFAINEcmd", "sendbuttonembed"]
	name = "mute"
	description = "mute selected user"
	optionIds = ["users"]
	botIds = ["1040761244442968185"]
	allow-users = ["mani123#7703"]

	#allow-roles = []
	[interaction.success]
		IsEphemeral = true
		actionId = "sendsuccessmessage"

	[interaction.error]
		IsEphemeral = true
		actionId = "senderrormessage"

	[interaction.option]

		[interaction.option.users]
			name = "firtsusersmute"
			description = "List of users2"
			type = "user"
			required = true

[[interaction]]
	actionsIds = ["unmutecommand", "UNDEFAINEcmd"]
	name = "unmute"
	description = "unmute selected user"
	optionIds = ["users2"]
	botIds = ["1040761244442968185"]
	allow-users = ["mani123#7703"]

	#allow-roles = []
	[interaction.success]
		IsEphemeral = true
		actionId = "sendsuccessmessage"

	[interaction.error]
		IsEphemeral = true
		actionId = "senderrormessage"

	[interaction.option]

		[interaction.option.users2]
			name = "firtsusersunmute"
			description = "List of users2"
			type = "user"
			required = true

