
# Configure command interactions
[[interaction]]
actionsIds = ["actionid1"]
name = "examplecommand"
successTitle = "Example command"
successDescription = "${interaction-user-mentioned} used command"
successIsEphemeral = true
description = "Command for example"
optionIds = [
    "users",
    "strings"
]
botIds = ["792689746156978207"]

    [interaction.option]
        name = "name"
        description = "Description"
        type = "none"

        [interaction.option.users]
            name = "user"
            description = "List of users"
            type = "user"
            required = true

        [interaction.option.strings]
            name = "adition"
            description = "List of strings"
            type = "string"
            required = false
            autocomplete = true
            autocompleteIds = [
                "stringsid1",
                "stringsid2"
            ]

[autocomplete.stringsid1]
    actionsIds = ["actionid1", "actionid2"]
[autocomplete.stringsid2]
    actionsIds = ["actionid1", "actionid2"]