color = "#000000"
description = "You cant use this command"
type = "SEND_EMBED"
title = "You cant use this command"

[[sub-action]]
	emoji = "U+1F600"
	id = "btn1"
	label = "This btn"
	type = "add-button"

